version: '3'   
services:
  frontend:
    build: frontend
    
    ports:
      - 4500:4500
  
    stdin_open: true
    container_name: frontend_gpt
    restart: always  
    volumes:
      - ./frontend:/app
      - /app/node_modules:./node_modules
    depends_on:
      -  backend

  backend:
    build: backend
    ports:
       - 3005:3005
    
    container_name: backend_gpt
    restart: always  
    volumes:
      - ./backend:/app
      - /app/node_modules:./node_modules
 